"""Re-run each published method on gpt-5.6-luna at full strength.

The point of the SFT comparison is the instruction-generation method, so every
baseline is generated by the same model we use, with the mechanism that made the
original work kept intact rather than approximated:

  self_instruct  ROUGE-L against the ENTIRE pool, not a bounded sample. The
                 original's filter is O(n) per candidate and that cost is real,
                 but weakening it here would understate the method.
  evol_instruct  WizardLM's own operator set -- five in-depth prompts plus
                 in-breadth mutation -- with the elimination step that discards
                 an evolution which failed to add information.
  persona_hub    The RELEASED persona catalogue, sampled from 50k real personas,
                 under Persona-Hub's 2-shot instruction-synthesis format. A
                 hand-written list of two dozen personas is not this method.

Same 175 seed tasks, same budget in generator calls, same model, same settings.
"""
from __future__ import annotations

import json
import os
import random
import re
import sys
import threading
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
PUB = HERE.parent / "public_corpora"
OUT = HERE / "data"
OUT.mkdir(exist_ok=True)

MODEL = "openai/gpt-5.6-luna"
URL = "https://openrouter.ai/api/v1/chat/completions"
KEY = os.environ["OPENROUTER_API_KEY"]
BUDGET = 2400
LOCK = threading.Lock()
SPEND = {"calls": 0, "in": 0, "out": 0}

# WizardLM's evolution operators, in-depth then in-breadth
EVOL_DEPTH = [
    "Please add one more constraint/requirement into #The Given Prompt#.",
    "If #The Given Prompt# contains inquiries about certain issues, the depth and "
    "breadth of the inquiry can be increased.",
    "Please replace general concepts with more specific concepts.",
    "If #The Given Prompt# can be solved with just a few simple thinking processes, "
    "please rewrite it to explicitly request multiple-step reasoning.",
    "Please add one more input/data requirement into #The Given Prompt#, making it "
    "harder to handle.",
]
EVOL_BREADTH = (
    "Create a brand new prompt inspired by #The Given Prompt#. It must belong to the "
    "same domain but be rarer, and of comparable length and difficulty."
)
EVOL_TMPL = (
    "I want you to act as a Prompt Rewriter.\nYour objective is to rewrite a given "
    "prompt into a more complex version to make well-known AI systems a bit harder "
    "to handle.\nBut the rewritten prompt must be reasonable, must be understood and "
    "responded to by humans, and must not omit the input in #The Given Prompt#.\n"
    "You SHOULD complicate the given prompt using the following method:\n{op}\n"
    "You should try your best not to make #Rewritten Prompt# become verbose; "
    "#Rewritten Prompt# can only add 10 to 20 words into #The Given Prompt#.\n"
    "'#The Given Prompt#', '#Rewritten Prompt#', 'given prompt' and 'rewritten "
    "prompt' are not allowed to appear in #Rewritten Prompt#.\n\n"
    "#The Given Prompt#:\n{prompt}\n\n#Rewritten Prompt#:\n"
)
PERSONA_TMPL = (
    "Here are two examples of instructions people give to an AI assistant:\n\n"
    "1. {ex1}\n\n2. {ex2}\n\nNow write ONE new instruction of a similar kind that "
    "the following person would plausibly give. Output only the instruction.\n\n"
    "Person: {persona}"
)
SELF_INSTRUCT_TMPL = (
    "You are asked to come up with a set of diverse task instructions. These "
    "instructions will be given to a GPT model and we will evaluate the model for "
    "completing the instructions.\n\nHere are the requirements:\n"
    "1. Try not to repeat the verb for each instruction to maximize diversity.\n"
    "2. The language used for the instruction also should be diverse.\n"
    "3. The type of instructions should be diverse.\n"
    "4. The instructions should be in English.\n"
    "5. The instructions should be 1 to 2 sentences long.\n\n"
    "List of 8 tasks:\n{shots}\n8. "
)


def call(prompt: str, temperature: float = 1.0, max_tokens: int = 400) -> str | None:
    body = json.dumps({"model": MODEL,
                       "messages": [{"role": "user", "content": prompt}],
                       "temperature": temperature, "max_tokens": max_tokens}).encode()
    for a in range(4):
        try:
            req = urllib.request.Request(
                URL, data=body, headers={"Authorization": f"Bearer {KEY}",
                                         "Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=180) as r:
                d = json.loads(r.read())
            u = d.get("usage", {})
            with LOCK:
                SPEND["calls"] += 1
                SPEND["in"] += u.get("prompt_tokens", 0)
                SPEND["out"] += u.get("completion_tokens", 0)
            return (d["choices"][0]["message"]["content"] or "").strip()
        except Exception:
            import time
            time.sleep(2 * (a + 1))
    return None


# ---------------------------------------------------------------- ROUGE-L
def lcs(a: list[str], b: list[str]) -> int:
    if not a or not b:
        return 0
    prev = [0] * (len(b) + 1)
    for x in a:
        cur = [0]
        for j, y in enumerate(b):
            cur.append(prev[j] + 1 if x == y else max(cur[j], prev[j + 1]))
        prev = cur
    return prev[-1]


def rouge_l(a: list[str], b: list[str]) -> float:
    l = lcs(a, b)
    if not l:
        return 0.0
    p, r = l / len(a), l / len(b)
    return 2 * p * r / (p + r)


def seeds() -> list[str]:
    out = []
    for line in (PUB / "seed_tasks.jsonl").read_text().splitlines():
        if line.strip():
            out.append(json.loads(line)["instruction"].strip())
    return out


def save(arm: str, texts: list[str]) -> None:
    p = OUT / f"instr_{arm}.jsonl"
    p.write_text("\n".join(json.dumps({"instruction": t}) for t in texts) + "\n")
    print(f"{arm}: wrote {len(texts)} instructions to {p.name}  "
          f"(calls={SPEND['calls']})", flush=True)


# ------------------------------------------------------------ self-instruct
def run_self_instruct() -> None:
    rng = random.Random(7)
    human = seeds()
    pool, pool_toks = [], []
    calls = 0
    while calls < BUDGET:
        batch = []
        with ThreadPoolExecutor(max_workers=16) as ex:
            futs = []
            for _ in range(min(16, BUDGET - calls)):
                shots = rng.sample(human, 6) + (rng.sample(pool, 2) if len(pool) >= 2 else [])
                rng.shuffle(shots)
                txt = "\n".join(f"{i+1}. {s}" for i, s in enumerate(shots[:7]))
                futs.append(ex.submit(call, SELF_INSTRUCT_TMPL.format(shots=txt)))
            for f in futs:
                batch.append(f.result())
                calls += 1
        for raw in batch:
            if not raw:
                continue
            for cand in re.split(r"\n\s*\d+\.\s*", "8. " + raw):
                cand = re.sub(r"^\s*\d+\.\s*", "", cand).strip()
                if not (12 < len(cand) < 500):
                    continue
                ct = cand.lower().split()
                # the original compares against the WHOLE pool
                if pool_toks and max(rouge_l(ct, r) for r in pool_toks) > 0.7:
                    continue
                pool.append(cand)
                pool_toks.append(ct)
        print(f"  self_instruct: {calls}/{BUDGET} calls, pool={len(pool)}", flush=True)
    save("fs_self_instruct", pool)


# ------------------------------------------------------------ evol-instruct
def run_evol() -> None:
    rng = random.Random(11)
    pool = list(seeds())
    calls = 0
    while calls < BUDGET:
        with ThreadPoolExecutor(max_workers=16) as ex:
            futs = []
            for _ in range(min(16, BUDGET - calls)):
                parent = rng.choice(pool)
                if rng.random() < 0.2:
                    p = EVOL_TMPL.format(op=EVOL_BREADTH, prompt=parent)
                else:
                    p = EVOL_TMPL.format(op=rng.choice(EVOL_DEPTH), prompt=parent)
                futs.append(ex.submit(call, p))
            for f in futs:
                out = f.result()
                calls += 1
                if not out:
                    continue
                out = out.strip().strip('"')
                # WizardLM's elimination: drop evolutions that did not evolve
                if len(out) < 15 or out.lower().startswith(("i'm sorry", "i cannot")):
                    continue
                if rouge_l(out.lower().split(), parent.lower().split()) > 0.95:
                    continue
                pool.append(out)
        print(f"  evol_instruct: {calls}/{BUDGET} calls, pool={len(pool)}", flush=True)
    save("fs_evol_instruct", [p for p in pool if p not in set(seeds())])


# -------------------------------------------------------------- persona-hub
def run_persona() -> None:
    rng = random.Random(13)
    personas = [json.loads(l)["input persona"].strip() for l in
                (PUB / "personahub_instruction.jsonl").read_text().splitlines() if l.strip()]
    print(f"  persona catalogue: {len(personas)} real personas", flush=True)
    human = seeds()
    out = []
    calls = 0
    while calls < BUDGET:
        with ThreadPoolExecutor(max_workers=16) as ex:
            futs = []
            for _ in range(min(16, BUDGET - calls)):
                ex1, ex2 = rng.sample(human, 2)
                futs.append(ex.submit(call, PERSONA_TMPL.format(
                    ex1=ex1, ex2=ex2, persona=rng.choice(personas))))
            for f in futs:
                t = f.result()
                calls += 1
                if t and 12 < len(t) < 800:
                    out.append(re.sub(r'^\s*(?:\d+\.|["“])\s*', "", t).strip().strip('"'))
        print(f"  persona_hub: {calls}/{BUDGET} calls, kept={len(out)}", flush=True)
    save("fs_persona_hub", out)


if __name__ == "__main__":
    for arm in (sys.argv[1:] or ["persona_hub", "evol_instruct", "self_instruct"]):
        print(f"=== {arm} ===", flush=True)
        {"self_instruct": run_self_instruct, "evol_instruct": run_evol,
         "persona_hub": run_persona}[arm]()
    print(f"TOTAL: {SPEND['calls']} calls, {SPEND['in']} in / {SPEND['out']} out")
